### ISSUE TITLE
Error with Python recommendation

### ISSUE THREAD

**Issue by M-Anwar** [M-Anwar/ARGEL#3]
Modified the way people upload ads, tried to keep as much compatibility with everything. Running the front end, I get this error with the python script. Only difference from before, is that now the ads returned have some more "tags" attached which are the location tags. Only one ad was uploaded if that makes a difference, the output of the script is below.

```
Session ID: 56c45ca24b32c8583dc6f4f1
The response contains 2 properties:
56c45ca24b32c8583dc6f4f1
Meta-Data Length: 0
1
Genders:[{u'confidence': 99.9999, u'value': u'Male'}]
Ages:[{u'range': 5, u'value': 26}]
Glasses?:[{u'confidence': 94.3417, u'value': u'Normal'}]
Smiling?[{u'value': 20.002}]
Crowd Test Array: [[  0.999999  26.         5.      ]]
[{"_id":"56c45c414b32c8583dc6f4ed","description":"Kovanda All the way","userid":"56b59a53f563db702f8
26854","adname":"Young Thugs","__v":0,"statistics":[],"metaData":["Young,thugs,4,lyfe,ye,yea"],"vide
oad":{"contentType":"image/png","filename":"c25f359b963641162875f081fea08484"},"tags":["-1, 20, 2","
{\"0\":{\"lat\":43.663297942696346,\"lng\":-79.39849412011716,\"radius\":25000},\"1\":{\"lat\":37.39
0890856417045,\"lng\":-121.94675087928772,\"radius\":25000},\"2\":{\"lat\":37.76854362092148,\"lng\"
:-122.44513750076294,\"radius\":25000}}"]}]
Predicting with:
[[ 0.999999  0.        0.        0.        1.        1.        0.        0.      ]]
Print Training: X and Y:..
[]
[]

Traceback (most recent call last):
  File "./facepp-python-sdk-master/process.py", line 39, in <module>
    recAdID = FaceRecog(session)
  File "D:\Documents\GitHub\ARGEL\facepp-python-sdk-master\FaceRec.py", line 105, in FaceRecog
    pred = K_near_age(X, test_x, 1)
  File "D:\Documents\GitHub\ARGEL\facepp-python-sdk-master\DecTree.py", line 213, in K_near_age
    clf.fit(X, y)
  File "D:\Program Files\Miniconda\lib\site-packages\sklearn\neighbors\base.py", line 778, in fit
    X, y = check_X_y(X, y, "csr", multi_output=True)
  File "D:\Program Files\Miniconda\lib\site-packages\sklearn\utils\validation.py", line 510, in chec
k_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "D:\Program Files\Miniconda\lib\site-packages\sklearn\utils\validation.py", line 407, in chec
k_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 8)) while a minimum of 1 is required.

```

**Comment by M-Anwar** [comment]
Okay awesome, looks good so far until we come up with a better way of keeping the tags.
